import { Camera, BookOpen, ChefHat, Search } from "lucide-react";

export const SITE_STATS = [
  { label: "Free Scans", val: "10/mo" },
  { label: "Recipes Generated", val: "1M+" },
  { label: "Cost to Start", val: "$0" },
  { label: "App Store Rating", val: "4.9" },
];

export const FEATURES = [
  {
    title: "Scan Your Pantry",
    description:
      "Photo recognition that actually works. Know what you have instantly.",
    icon: Camera,
    limit: "10 scans/mo free",
  },
  {
    title: "AI Chef Suggestions",
    description:
      "Turn random ingredients into a gourmet meal. Zero food waste.",
    icon: ChefHat,
    limit: "5 meals/mo free",
  },
  {
    title: "Search Any Dish",
    description:
      "Find any recipe instantly. Filter by cuisine, time, or dietary needs.",
    icon: Search,
    limit: "Unlimited searches",
  },
  {
    title: "Digital Cookbook",
    description: "Save your favorites. Export as PDF. Share with family.",
    icon: BookOpen,
    limit: "3 saves/mo free",
  },
];

export const HOW_IT_WORKS_STEPS = [
  {
    step: "01",
    title: "Scan",
    desc: "Point camera at fridge. AI identifies ingredients.",
  },
  {
    step: "02",
    title: "Select",
    desc: "Choose a generated recipe based on your mood.",
  },
  {
    step: "03",
    title: "Savor",
    desc: "Follow simple steps. Eat delicious food.",
  },
];

// Helper function for category emojis
export function getCategoryEmoji(category) {
  const emojiMap = {
    Beef: "🥩",
    Chicken: "🍗",
    Dessert: "🍰",
    Lamb: "🍖",
    Miscellaneous: "🍴",
    Pasta: "🍝",
    Pork: "🥓",
    Seafood: "🦐",
    Side: "🥗",
    Starter: "🥟",
    Vegan: "🥬",
    Vegetarian: "🥕",
    Breakfast: "🍳",
    Goat: "🐐",
  };
  return emojiMap[category] || "🍽️";
}

// Helper function for country codes (used with flag-icons CSS, e.g. <span className={`fi fi-${code}`} />)
export function getCountryCode(country) {
  const codeMap = {
    Afghan: "af",
    Albanian: "al",
    Algerian: "dz",
    Andorran: "ad",
    Angolan: "ao",
    "Antiguan, Barbudan": "ag",
    Argentine: "ar",
    Argentinian: "ar",
    Armenian: "am",
    Aruban: "aw",
    Australian: "au",
    Austrian: "at",
    Azerbaijani: "az",
    Bahamian: "bs",
    Bahraini: "bh",
    Bangladeshi: "bd",
    Barbadian: "bb",
    Belarusian: "by",
    Belgian: "be",
    Belizean: "bz",
    Beninese: "bj",
    Bermudian: "bm",
    Bhutanese: "bt",
    Bolivian: "bo",
    "Bosnian, Herzegovinian": "ba",
    Motswana: "bw",
    Brazilian: "br",
    Bruneian: "bn",
    Bulgarian: "bg",
    Burkinabe: "bf",
    Burundian: "bi",
    Cambodian: "kh",
    Cameroonian: "cm",
    Canadian: "ca",
    "Cape Verdian": "cv",
    Caymanian: "ky",
    "Central African": "cf",
    Chadian: "td",
    Chilean: "cl",
    Chinese: "cn",
    Colombian: "co",
    "Costa Rican": "cr",
    Croatian: "hr",
    Cuban: "cu",
    Cypriot: "cy",
    Czech: "cz",
    Danish: "dk",
    Djibouti: "dj",
    Dominican: "do",
    Congolese: "cd",
    Ecuadorean: "ec",
    Egyptian: "eg",
    Salvadoran: "sv",
    "Equatorial Guinean": "gq",
    Eritrean: "er",
    Estonian: "ee",
    Ethiopian: "et",
    Faroese: "fo",
    Fijian: "fj",
    Finnish: "fi",
    French: "fr",
    Gabonese: "ga",
    Gambian: "gm",
    Georgian: "ge",
    German: "de",
    Ghanaian: "gh",
    Gibraltar: "gi",
    Greek: "gr",
    Greenlandic: "gl",
    Grenadian: "gd",
    Guadeloupian: "gp",
    Guamanian: "gu",
    Guatemalan: "gt",
    "Channel Islander": "je",
    Guinean: "gn",
    "Guinea-Bissauan": "gw",
    Guyanese: "gy",
    Haitian: "ht",
    Honduran: "hn",
    "Hong Konger": "hk",
    Hungarian: "hu",
    Icelander: "is",
    Indian: "in",
    Indonesian: "id",
    Iranian: "ir",
    Iraqi: "iq",
    Irish: "ie",
    Israeli: "il",
    Italian: "it",
    Ivorian: "ci",
    Jamaican: "jm",
    Japanese: "jp",
    Jordanian: "jo",
    Kazakhstani: "kz",
    Kenyan: "ke",
    Kosovar: "xk",
    Kuwaiti: "kw",
    Kirghiz: "kg",
    Laotian: "la",
    Latvian: "lv",
    Lebanese: "lb",
    Mosotho: "ls",
    Liberian: "lr",
    Libyan: "ly",
    Liechtensteiner: "li",
    Lithuanian: "lt",
    Luxembourger: "lu",
    Malagasy: "mg",
    Malawian: "mw",
    Malaysian: "my",
    Maldivan: "mv",
    Malian: "ml",
    Maltese: "mt",
    Mauritian: "mu",
    Mexican: "mx",
    Moldovan: "md",
    Mongolian: "mn",
    Montenegrin: "me",
    Moroccan: "ma",
    Mozambican: "mz",
    Burmese: "mm",
    Namibian: "na",
    Nepalese: "np",
    Dutch: "nl",
    "New Zealander": "nz",
    Nicaraguan: "ni",
    Nigerien: "ne",
    Nigerian: "ng",
    "North Korean": "kp",
    Macedonian: "mk",
    Norwegian: "no",
    Omani: "om",
    Pakistani: "pk",
    Palestinian: "ps",
    Panamanian: "pa",
    "Papua New Guinean": "pg",
    Paraguayan: "py",
    Peruvian: "pe",
    Filipino: "ph",
    Polish: "pl",
    Portuguese: "pt",
    "Puerto Rican": "pr",
    Qatari: "qa",
    Romanian: "ro",
    Russian: "ru",
    Rwandan: "rw",
    "Saint Lucian": "lc",
    Samoan: "ws",
    Sammarinese: "sm",
    "Saudi Arabian": "sa",
    Senegalese: "sn",
    Serbian: "rs",
    Seychellois: "sc",
    "Sierra Leonean": "sl",
    Singaporean: "sg",
    Slovak: "sk",
    Slovakian: "sk",
    Slovene: "si",
    "Solomon Islander": "sb",
    Somali: "so",
    "South African": "za",
    "South Korean": "kr",
    "South Sudanese": "ss",
    Spanish: "es",
    "Sri Lankan": "lk",
    Sudanese: "sd",
    Surinamer: "sr",
    Swedish: "se",
    Swiss: "ch",
    Syrian: "sy",
    Taiwanese: "tw",
    Tadzhik: "tj",
    Tanzanian: "tz",
    Thai: "th",
    Togolese: "tg",
    Tongan: "to",
    Trinidadian: "tt",
    Tunisian: "tn",
    Turkish: "tr",
    Turkmen: "tm",
    Tuvaluan: "tv",
    Ugandan: "ug",
    Ukrainian: "ua",
    Emirati: "ae",
    British: "gb",
    American: "us",
    Uruguayan: "uy",
    Uzbekistani: "uz",
    "Ni-Vanuatu": "vu",
    Venezuelan: "ve",
    Vietnamese: "vn",
    Yemeni: "ye",
    Zambian: "zm",
    Zimbabwean: "zw",
  };

  return codeMap[country] ?? null;
}